#!/bin/sh
#
# A git hook to make sure user.email exists before committing

EMAIL=$(git config user.email)

if [ -z "$EMAIL" ]; then
    # user.email is empty
    echo "ERROR: [pre-commit hook] Aborting commit because user.email is missing."
    echo "Configure user.email for this repository by running: '$ git config user.email name@example.com'."
    echo "Make sure not to configure globally and use the correct email."
    exit 1
else
    # user.email is not empty
    exit 0
fi
