[[plugins]]
repo = 'guns/xterm-color-table.vim'
on_cmd = ['XtermColorTable']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo = 'leshill/vim-json'
on_ft = ['javascript', 'json']

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'Rip-Rip/clang_complete'
on_ft = [ 'c', 'cpp' ]
hook_add = '''
  let g:clang_library_path='/usr/lib/llvm-3.8/lib'
  let g:clang_complete_auto = 0
  let g:clang_auto_select = 0
  let g:clang_omnicppcomplete_compliance = 0
  let g:clang_make_default_keymappings = 0
  "let g:clang_use_library = 1
'''

[[plugins]]
repo = 'lyuts/vim-rtags'
on_ft = [ 'c', 'cpp' ]
hook_add = '''
  let g:rtagsUserLocationList = 0
'''
